### PR TITLE
PFM-ISSUE-28058 Pin-versions-of-dependencies-in-cplace-asc

### PR DESCRIPTION
**Pull request by stefancplace**
Resolves [PFM-ISSUE-28058](https://base.cplace.io/pages/lor3e07ys76napryn50wkw9o1/PFM-ISSUE-28058-Pin-versions-of-dependencies-in-cplace-asc#id_wsrqdlqi9cus7fztqfsfa3gnz=newOverview)

### CODE REVIEW

**Review by Kaltenbach — APPROVED** [review]
👍

**Review by Kaltenbach — APPROVED** [review]

**Comment by Kaltenbach** [comment]
@stefancplace out of curiosity has I struggle with the meaning of `2.x.x`:

-  the new `2.x.x` version `2.0.17` 
-  the new `2.1.x` version `2.1.6`
-  the new `2.0.x` version  `2.0.26`

in the skeleton we use [`"@cplace/asc-local": "~2.0"`](https://github.com/collaborationFactory/cplace-customer-repo-skeleton/blob/8b5705701605d9dd4a9bbc155e5361e3b0438ac8/package.json#L11C5-L11C32) for cplace `version/23.2`.
I guess this now resolves to `2.0.x` ->  `2.0.26` due to the higher patch version.

From the [npm docu](https://docs.npmjs.com/about-semantic-versioning) I understand that `2.x.x` is the same as the latest minor and patch version of major 2.  In that range, this would be `2.1.6`.

**Comment by stefancplace** [comment]
> @stefancplace out of curiosity as I struggle with the meaning of `2.x.x`:
> 
> * the new `2.x.x` version `2.0.17`
> * the new `2.1.x` version `2.1.6`
> * the new `2.0.x` version  `2.0.26`
> 
> in the skeleton we use [`"@cplace/asc-local": "~2.0"`](https://github.com/collaborationFactory/cplace-customer-repo-skeleton/blob/8b5705701605d9dd4a9bbc155e5361e3b0438ac8/package.json#L11C5-L11C32) for cplace `version/23.2`. I guess this now resolves to `2.0.x` -> `2.0.26` due to the higher patch version.
> 
> From the [npm docu](https://docs.npmjs.com/about-semantic-versioning) I understand that `2.x.x` is the same as the latest minor and patch version of major 2. In that range, this would be `2.1.6`.

This exceeds my knowledge @slaven3kopic can you provide guidance here?

**Comment by stefancplace** [comment]
just talked to Slaven, he mentioned 2.x.x is not needed

**Comment by stefancplace** [comment]
2.x.x is no longer needed

**Pull request closed without merging**
